# Generated by Django 5.0.4 on 2024-05-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appachei', '0002_remove_usuario_senha_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
